name: ${project.name}
version: ${project.version}
main: net.azisaba.yukielevator.${project.name}
description: ${project.description}
website: ${project.url}
author: YukiLeafX
api-version: 1.12
permissions:
  yukielevator.use:
    default: true
    children:
      yukielevator.up: true
      yukielevator.down: true
  yukielevator.up:
    default: true
  yukielevator.down:
    default: true
